name: CooperativeEndAccess
version: ${version}
main: io.github.ganyuke.cooperativeEndAccess.CooperativeEndAccess
api-version: ${paper_version}
authors: [ ganyuke ]
description: Ensure that opening the End for the first time is always a group activity.
website: https://github.com/ganyuke/CooperativeEndAccess
